//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PleaseIgnore.IntelMap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PleaseIgnore.IntelMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory {0} does not exist..
        /// </summary>
        internal static string ArgumentException_DirNotExist {
            get {
                return ResourceManager.GetString("ArgumentException_DirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAsyncResult object did not come from the corresponding async method on this type..
        /// </summary>
        internal static string ArgumentException_WrongObject {
            get {
                return ResourceManager.GetString("ArgumentException_WrongObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Name).
        /// </summary>
        internal static string IntelChannel_NoName {
            get {
                return ResourceManager.GetString("IntelChannel_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Name={1}, Status={2}.
        /// </summary>
        internal static string IntelChannel_ToString {
            get {
                return ResourceManager.GetString("IntelChannel_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TEST Intel Map server responded in an expected manner..
        /// </summary>
        internal static string IntelException {
            get {
                return ResourceManager.GetString("IntelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Connected ({1} Users; {2} Reports Sent).
        /// </summary>
        internal static string IntelSession_Connected {
            get {
                return ResourceManager.GetString("IntelSession_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Disposed ({2} Reports Sent).
        /// </summary>
        internal static string IntelSession_Disposed {
            get {
                return ResourceManager.GetString("IntelSession_Disposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to begin initiation after component has been started..
        /// </summary>
        internal static string InvalidOperation_InitRunning {
            get {
                return ResourceManager.GetString("InvalidOperation_InitRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be called once for each asynchronous operation..
        /// </summary>
        internal static string InvalidOperation_MultipleCalls {
            get {
                return ResourceManager.GetString("InvalidOperation_MultipleCalls", resourceCulture);
            }
        }
    }
}
